import time
from sqlalchemy import create_engine, Column, Integer, String, Float, JSON, Boolean, BigInteger
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class ManagedTrade(Base):
    __tablename__ = 'managed_trades'

    id = Column(Integer, primary_key=True)
    # A unique ID for the trade, can be from the exchange or generated by us
    trade_id = Column(String, unique=True, nullable=False, index=True)
    symbol = Column(String, nullable=False, index=True)
    
    # --- Trade State ---
    # 'pending', 'active', 'closing', 'closed'
    status = Column(String, nullable=False, default='pending', index=True)
    direction = Column(String, nullable=False) # 'LONG' or 'SHORT'

    # --- Entry Details ---
    entry_price = Column(Float)
    qty = Column(Float)
    entry_timestamp = Column(BigInteger, default=lambda: int(time.time() * 1000))
    
    # The original analysis/reasoning from the Arsenal bot
    entry_reasoning = Column(JSON)

    # Market structure at time of entry for BOS checks
    swing_highs = Column(JSON)
    swing_lows = Column(JSON)

    # --- Risk Management ---
    initial_stop_loss = Column(Float, nullable=False)
    current_stop_loss = Column(Float, nullable=False)
    sl_moved_to_breakeven = Column(Boolean, default=False, nullable=False)
    take_profit = Column(Float, nullable=False)

    # --- Trailing Stop ---
    trailing_stop_activated = Column(Boolean, default=False, nullable=False)
    trailing_stop_distance = Column(Float)
    progressive_tp_level_achieved = Column(Integer, default=0, nullable=False)

    # --- Performance Tracking ---
    exit_reason = Column(String)
    exit_price = Column(Float)
    exit_timestamp = Column(BigInteger)
    pnl = Column(Float)
    pnl_percent = Column(Float)
    
    # Maximum Adverse Excursion (how much the trade went against us)
    max_adverse_excursion = Column(Float, default=0.0)
    # Maximum Favorable Excursion (how much the trade went in our favor)
    max_favorable_excursion = Column(Float, default=0.0)

    # --- Timestamps ---
    created_at = Column(BigInteger, default=lambda: int(time.time() * 1000))
    updated_at = Column(BigInteger, onupdate=lambda: int(time.time() * 1000))

    def __repr__(self):
        return f"<ManagedTrade(id={self.trade_id}, symbol='{self.symbol}', direction='{self.direction}', status='{self.status}', pnl={self.pnl})>"


class SymbolCvdBaseline(Base):
    __tablename__ = 'symbol_cvd_baselines'

    symbol = Column(String, primary_key=True, index=True)
    
    # Using Welford's online algorithm for stable variance calculation
    mean_slope = Column(Float, nullable=False, default=0.0)
    m2 = Column(Float, nullable=False, default=0.0) # Sum of squares of differences from the current mean
    count = Column(Integer, nullable=False, default=0)

    updated_at = Column(BigInteger, default=lambda: int(time.time() * 1000), onupdate=lambda: int(time.time() * 1000))

    def __repr__(self):
        return f"<SymbolCvdBaseline(symbol='{self.symbol}', mean_slope={self.mean_slope:.2f}, count={self.count})>"
