"""
Arsenal Signal Logger
=====================
This module provides a persistent logging mechanism for every trade signal
generated by the Arsenal brains that is sent to Horus for confirmation.

It captures the complete state of the market and the brain's reasoning at the
moment of decision, storing it for future analysis, backtesting, and tuning
of both Arsenal and Horus.
"""

import json
import aiofiles
from datetime import datetime
from dataclasses import is_dataclass, asdict
import pandas as pd
import numpy as np
import logging

logger = logging.getLogger(__name__)

class EnhancedJSONEncoder(json.JSONEncoder):
    """
    A custom JSON encoder to handle complex types found in Arsenal's
    decision objects, such as dataclasses, datetime, and numpy types.
    """
    def default(self, o):
        if is_dataclass(o):
            return asdict(o)
        if isinstance(o, datetime):
            return o.isoformat()
        if isinstance(o, pd.Timestamp):
            return o.isoformat()
        if isinstance(o, (np.integer, np.floating, np.bool_)):
            return o.item()
        if isinstance(o, pd.DataFrame):
            return o.to_dict(orient='split')
        # Add handling for other potential types here if necessary
        return super().default(o)

class SignalLogger:
    """
    Logs Arsenal trade signals to a persistent JSON Lines file.
    """
    def __init__(self, symbol: str):
        self.symbol = symbol
        self.log_file = f'arsenal_signals_{self.symbol}.jsonl'
        logger.info(f"SignalLogger initialized. Logging signals to: {self.log_file}")

    async def log_signal(self, decision, horus_confirmation: bool, horus_rejection_reason: str):
        """
        Logs a single trade signal and its context to the file.

        Args:
            decision (IntelligentDecision): The decision object from the brain.
            horus_confirmation (bool): The result from Horus confirmation.
            horus_rejection_reason (str): The reason for Horus's decision.
        """
        try:
            log_entry = {
                "log_timestamp_utc": datetime.utcnow(),
                "signal_timestamp_utc": decision.decision_timestamp,
                "symbol": self.symbol,
                "decision": decision,
                "horus_confirmation": horus_confirmation,
                "horus_rejection_reason": horus_rejection_reason,
                # The full market_intel is nested inside the decision object
            }

            # Serialize the log entry to a JSON string
            log_line = json.dumps(log_entry, cls=EnhancedJSONEncoder)

            # Asynchronously append to the file
            async with aiofiles.open(self.log_file, mode='a') as f:
                await f.write(log_line + '\n')

            logger.info(f"Successfully logged signal for {decision.direction} at {decision.entry_zone[0]:.2f}. Horus Confirmation: {horus_confirmation}")

        except Exception as e:
            logger.error(f"Failed to log signal: {e}", exc_info=True)

